config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :students
  # get 'home/index'
  #root 'home#index'
  get 'home/about'
  root 'students#index'

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  #Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :students
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

  def about
      @about_me = "My Name is Boubacar I am Software Developper"

  end 
 end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user,only: [:edit, :update, :destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    #@student = Student.new
    @student = current_user.students.build
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    #@student = Student.new(student_params)
    @student = current_user.students.build(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @student = current_user.students.find_by(id: params[:id])
    redirect_to students_path, notice: "Not Authorized To Edit this Student" if @student.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Students Registry App', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
           <%= link_to 'About Us', home_about_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
           <%= link_to 'Students', students_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>

            <li class="nav-item">
               <%= link_to 'Add Student', new_student_path, class: "nav-link" %>
            </li>
         
            <li class="nav-item">
               <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>

            <li class="nav-item">
               <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
            </li>

         <% else %>

            <li class="nav-item">
               <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
            </li>

            <li class="nav-item">
               <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
            </li>

        <% end %>              

      </ul>

      <form class="d-flex" role="search">
         <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
         <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h2><b>About Us...!</b></h2>

<p>

    <%= @about_me %>

</p>

app/views/home/index.html.erb
<h1>Hello Test</h1>
my first Rails Web page.....!

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Firststart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'turbo', type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'home/header' %>

    <div class="container">
      <%if notice%> 
        <%= render 'layouts/alerts'%>
      <%end%>
      <br>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter account" %>
  </div>

  <div>
    <% form.label :User, style: "display: block" %>
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <br>
  <div>
    <%= form.submit class:'btn btn-success'%>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>First name:</strong>
    <%= student.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= student.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= student.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= student.twitter %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student, class:"btn btn-secondary" %> |
  <%= link_to "Back to students", students_path, class:"btn btn-dark" %>
</div>

app/views/students/index.html.erb
<% if user_signed_in? %>


<div class='container-fluid'>
    <h3 class=''>Students List</h3>
      <table class="table table-striped table-bordered">
        <thead class="thead-dark" >
          <tr>
            <th>Name</th>
              
            <th>Email</th>
            <th>Phone</th>
            <th>Twitter</th>
            <th>User Id</th>
            <th colspan="2">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
            <tr>
              <td>        
                <%= link_to student.first_name + ' ' + student.last_name, student %>
              </td>
              <td> <%= student.email %> </td> 
              <td> <%= student.phone %> </td> 
              <td> <%= student.twitter %> </td>
              <td> <%= student.user_id %> </td>
              
              <% if student.user == current_user %>
              <!--<td><%= link_to 'Edit', edit_student_path(student) %></td>-->
              <td><%= button_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-outline-danger btn-sm' %></td>   
                <!--<%= link_to 'Delete this student', student, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"  %>
                <td></td>
                <td></td>-->
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
  <br> 

  <p>
    <%= link_to "New student", new_student_path, class:"btn btn-secondary" %>
    <!--<button type="button" class="btn btn-secondary">
    Secondary
    </button>-->
  </p>
  <% else %>

  <h1>Hello Test</h1>
    my first Rails Web page.....!
  <% end %>

</div>

app/views/students/new.html.erb
<h1>Add New student</h1>
<br>
<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path, class:"btn btn-dark" %>
</div>

app/views/students/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"> <%= @student.first_name%> <%= @student.last_name %> </h1>
  <br/>
  <p>
     <%= @student.email %> |
     <%= @student.phone %> |
     <%= @student.twitter %>
  </p>
  <hr class="my-4">

  <br/>
  <%= link_to "Edit this student", edit_student_path(@student), class:"btn btn-secondary" %> |
  <%= link_to "Back to students", students_path, class:"btn btn-dark" %>

<p>
  <%= button_to "Destroy this student", @student, method: :delete, class:"btn btn-danger" %>
</p> 
</div>